### ISSUE TITLE
Version 3 no longer supports the condition form of depends_on.

### ISSUE THREAD

**Issue by nurhanhasan** [peter-evans/docker-compose-healthcheck#10]
Take care, this won't work with compose file version 3.

As per documentation:

Version 3 no longer supports the condition form of depends_on.

**Comment by nurhanhasan** [comment]
Below works fine, use variables if you configured the container with custom values.

healthcheck:
  test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB]"]
  interval: 10s
  timeout: 5s
  retries: 5

**Comment by peter-evans** [comment]
Thank you @nurhun 

There is already an issue about this here: https://github.com/peter-evans/docker-compose-healthcheck/issues/3
