### ISSUE TITLE
healthcheck condition is not supported in docker compose file v3

### ISSUE THREAD

**Issue by mattscilipoti** [peter-evans/docker-compose-healthcheck#15]
Thanks for providing this resource. While attempting to get it working on my system, I think I have identified that it is not supported in docker compose v3. I found the first hint here: https://stackoverflow.com/a/59072727. I looked through the docs for v3 and cannot find "condition" or "service_healthy" (https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on). 
Is it still working for you in v3? If not, maybe you could add a comment that it is supported by v2?

Here's their reasoning (from https://docs.docker.com/compose/startup-order/): 
> The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.
> To handle this, design your application to attempt to re-establish a connection to the database after a failure. If the application retries the connection, it can eventually connect to the database.

Thanks for directing me to pg_isready

**Comment by peter-evans** [comment]
Hi @mattscilipoti 

Please see issue https://github.com/peter-evans/docker-compose-healthcheck/issues/3 where this has been resolved.
