### ISSUE TITLE
Can this work with v3 of docker compose?

### ISSUE THREAD

**Issue by ghost** [peter-evans/docker-compose-healthcheck#3]
Since docker compose won't support the `condition` form of `depends_on` can something like healthcheck works yet?

reference:
https://docs.docker.com/compose/compose-file/#depends_on

**Comment by peter-evans** [comment]
No, unfortunately this does not work with v3 of docker compose. From v3 they are not supporting the `condition` syntax, as you have pointed out. Docker want to move away from `docker-compose` to the integrated `docker stack` and Swarm services. When designing how these should work it seems that Docker have made a conscious decision not to support features that wait for containers to be in a "ready" state. They argue that applications depending on other systems should be resilient to failure.

This is a couple of paragraphs taken from the documentation [here](https://docs.docker.com/compose/startup-order/) that explains their reasoning.
> The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.
> 
> To handle this, your application should attempt to re-establish a connection to the database after a failure. If the application retries the connection, it should eventually be able to connect to the database.

So the options are:
1. Keep using the v2 format
2. Use a tool like [wait-for-it](https://github.com/vishnubob/wait-for-it) or [dockerize](https://github.com/jwilder/dockerize)
3. Make your application resilient to database failure and able to retry it's connection on startup

There is some discussion about this issue [here](https://github.com/docker/compose/issues/4305) and [here](https://github.com/moby/moby/issues/30404).

**Comment by satrapu** [comment]
You could invoke Docker API, as documented [here](https://crossprogramming.com/2018/05/13/controlling-service-startup-order-in-docker-compose.html#docker_engine_api).

**Comment by blevine** [comment]
You might want to make a note in your README that this solution doesn't work as of docker-compose V3

**Comment by peter-evans** [comment]
Added a note to the readme about this issue. Thanks.

**Comment by srstsavage** [comment]
This __is__ supported in newer versions of docker-compose which support the [compose specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md). Verified with docker-compose 1.28.4 here.

cc @unparalleled-js

**Comment by peter-evans** [comment]
@shane-axiom Thanks for letting me know! I had no idea about this change.

> Docker Compose 1.27.0+ implements the format defined by the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md). Previous Docker Compose versions have support for several Compose file formats – 2, 2.x, and 3.x. The Compose specification is an unified 2.x and 3.x file format, aggregating properties across these formats.

ref: https://docs.docker.com/compose/compose-file/

It aggregates properties across all the past formats, so you can now use the 2.x `condition` syntax with the latest version of compose. Perhaps it only works if you don't [specify the version](https://github.com/peter-evans/docker-compose-healthcheck/blob/master/docker-compose.yml#L1) at the top of the compose file? I see that the `version` property is optional now. Anyway, I'll test it out and update this repository.

**Comment by peter-evans** [comment]
Tested and updated the readme. Basically, it doesn't matter what the `version` property is set to anymore because it's not used. Recent versions of Docker Compose follow the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md) which allows features from previous versions of Compose to be used together.

I think we can consider this issue resolved.
